CREATE TABLE [dbo].[COMMISSION_EVENT](
	[ID] [uniqueidentifier] NOT NULL,
	[COMMISSION_ID] [uniqueidentifier] NOT NULL,
	[DATE] [datetime] NOT NULL,
	[STATE] [nvarchar](20) NOT NULL,
	[ANNOTATION] [nvarchar](200) NULL,
 CONSTRAINT [PK_COMMISSION_EVENT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

ALTER TABLE [dbo].[COMMISSION_EVENT] ADD  CONSTRAINT [DF_COMMISSION_EVENT_ID]  DEFAULT (newid()) FOR [ID];

ALTER TABLE [dbo].[COMMISSION_EVENT]  WITH CHECK ADD  CONSTRAINT [FK_COMMISSION_EVENTS_COMMISSION] FOREIGN KEY([COMMISSION_ID])
REFERENCES [dbo].[COMMISSION] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE [dbo].[COMMISSION_EVENT] CHECK CONSTRAINT [FK_COMMISSION_EVENTS_COMMISSION];
