CREATE TABLE [dbo].[STATISTICS](
	[ID] [uniqueidentifier] NOT NULL,
	[PLUGIN] [nvarchar](50) NOT NULL,
	[NO] [int] NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_STATISTICS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


