CREATE TABLE [dbo].[ARTIST](
	[ID] [uniqueidentifier] NOT NULL,
	[MANDATOR_ID] [uniqueidentifier] NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[IS_ARTIST] [bit] NOT NULL,
	[LEGACY_ID] [int] NULL,
 CONSTRAINT [PK_ARTISTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

ALTER TABLE [dbo].[ARTIST] ADD  CONSTRAINT [DF_ARTISTS_ID]  DEFAULT (newid()) FOR [ID];

ALTER TABLE [dbo].[ARTIST]  WITH CHECK ADD  CONSTRAINT [FK_ARTIST_MANDATOR] FOREIGN KEY([MANDATOR_ID])
REFERENCES [dbo].[MANDATOR] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE [dbo].[ARTIST] CHECK CONSTRAINT [FK_ARTIST_MANDATOR];
