CREATE TABLE [dbo].[COMMUNICATION](
	[ID] [uniqueidentifier] NOT NULL,
	[ARTIST_ID] [uniqueidentifier] NOT NULL,
	[CHANNEL] [nvarchar](50) NOT NULL,
	[ADDRESS] [nvarchar](100) NOT NULL,
	[ANNOTATION] [nvarchar](150) NULL,
	[LEGACY_ID] [int] NULL,
 CONSTRAINT [PK_COMMUNICATION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

ALTER TABLE [dbo].[COMMUNICATION] ADD  CONSTRAINT [DF_COMMUNICATION_ID]  DEFAULT (newid()) FOR [ID];

ALTER TABLE [dbo].[COMMUNICATION]  WITH CHECK ADD  CONSTRAINT [FK_COMMUNICATION_ARTIST] FOREIGN KEY([ARTIST_ID])
REFERENCES [dbo].[ARTIST] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE [dbo].[COMMUNICATION] CHECK CONSTRAINT [FK_COMMUNICATION_ARTIST];
