CREATE TABLE [dbo].[MANDATOR](
	[ID] [uniqueidentifier] NOT NULL,
	[NAME] [nvarchar](50) NULL,
 CONSTRAINT [PK_MANDATOR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

ALTER TABLE [dbo].[MANDATOR] ADD  CONSTRAINT [DF_MANDATOR_ID]  DEFAULT (newid()) FOR [ID];
