CREATE TABLE [dbo].[STATISTICS](
	[ID] [uniqueidentifier] NOT NULL,
	[NO] [int] NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[SQL_VIEW] [nvarchar](100) NOT NULL,
	[SQL_ORDER] [nvarchar](150) NULL,
 CONSTRAINT [PK_STATISTICS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

ALTER TABLE [dbo].[STATISTICS] ADD  CONSTRAINT [DF_STATISTICS_ID]  DEFAULT (newid()) FOR [ID];


