CREATE TABLE [dbo].[TEXT_BACKUP](
	[BAK_ID] [int] IDENTITY(1,1) NOT NULL,
	[BAK_DATE] [datetime] NOT NULL,
	[BAK_DATA] [varbinary](max) NOT NULL,
	[BAK_LINES] [int] NOT NULL,
	[ANNOTATION] [nvarchar](250) NULL,
 CONSTRAINT [PK__TEXT_BAC__02B39DC71D9EBC87] PRIMARY KEY CLUSTERED 
(
	[BAK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];
