CREATE TABLE [dbo].[UPLOAD](
	[ID] [uniqueidentifier] NOT NULL,
	[EVENT_ID] [uniqueidentifier] NOT NULL,
	[NO] [int] NOT NULL,
	[PAGE] [nvarchar](100) NULL,
	[URL] [nvarchar](150) NULL,
	[PROHIBIT] [bit] NOT NULL,
	[ANNOTATION] [nvarchar](100) NULL,
	[LEGACY_ID] [int] NULL,
 CONSTRAINT [PK_UPLOADS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

ALTER TABLE [dbo].[UPLOAD] ADD  CONSTRAINT [DF_UPLOADS_ID]  DEFAULT (newid()) FOR [ID];

ALTER TABLE [dbo].[UPLOAD]  WITH CHECK ADD  CONSTRAINT [FK_UPLOAD_EVENT] FOREIGN KEY([EVENT_ID])
REFERENCES [dbo].[COMMISSION_EVENT] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE [dbo].[UPLOAD] CHECK CONSTRAINT [FK_UPLOAD_EVENT];
